"""drop colecciones e interacciones

Revision ID: 1775df73146f
Revises: 4f05a8171f56
Create Date: 2025-05-12 15:50:05.097911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1775df73146f'
down_revision: Union[str, None] = '4f05a8171f56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coleccion_articulo_propio')
    op.drop_table('coleccion_outfit')
    op.drop_index('ix_colecciones_id', table_name='colecciones')
    op.drop_table('colecciones')
    op.drop_index('ix_interacciones_id', table_name='interacciones')
    op.drop_table('interacciones')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interacciones',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tipo', postgresql.ENUM('BUSQUEDA', 'CONSULTAR', 'GUARDAR', 'ENLACE', name='tipointeraccionenum'), autoincrement=False, nullable=False),
    sa.Column('fecha', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('busqueda', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name='interacciones_usuario_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='interacciones_pkey')
    )
    op.create_index('ix_interacciones_id', 'interacciones', ['id'], unique=False)
    op.create_table('colecciones',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('colecciones_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('publica', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('colaborativa', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name='colecciones_usuario_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='colecciones_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_colecciones_id', 'colecciones', ['id'], unique=False)
    op.create_table('coleccion_outfit',
    sa.Column('coleccion_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('outfit_propio_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['coleccion_id'], ['colecciones.id'], name='coleccion_outfit_coleccion_id_fkey'),
    sa.ForeignKeyConstraint(['outfit_propio_id'], ['outfits_propios.id'], name='coleccion_outfit_outfit_propio_id_fkey')
    )
    op.create_table('coleccion_articulo_propio',
    sa.Column('coleccion_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('articulo_propio_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['articulo_propio_id'], ['articulos_propios.id'], name='coleccion_articulo_propio_articulo_propio_id_fkey'),
    sa.ForeignKeyConstraint(['coleccion_id'], ['colecciones.id'], name='coleccion_articulo_propio_coleccion_id_fkey')
    )
    # ### end Alembic commands ###
