"""add foto field to ArticuloPropio

Revision ID: 33f870ca7a9d
Revises: 375dfeb820fe
Create Date: 2025-04-25 11:02:02.634880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33f870ca7a9d'
down_revision: Union[str, None] = '375dfeb820fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'articulo_propio_color', 'color_enum_items', ['color'], ['color'])
    op.create_foreign_key(None, 'articulo_propio_temporada', 'temporada_enum_items', ['temporada'], ['temporada'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articulo_propio_temporada', type_='foreignkey')
    op.drop_constraint(None, 'articulo_propio_color', type_='foreignkey')
    # ### end Alembic commands ###
