"""add foto_perfil to usuario

Revision ID: 37e9b34aa242
Revises: c2f3b1033281
Create Date: 2025-05-16 18:34:33.988370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37e9b34aa242'
down_revision: Union[str, None] = 'c2f3b1033281'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('foto_perfil', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'foto_perfil')
    # ### end Alembic commands ###
