"""collage outfits

Revision ID: 4792a2082222
Revises: 4d13a73675aa
Create Date: 2025-05-24 21:41:58.191239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4792a2082222'
down_revision: Union[str, None] = '4d13a73675aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outfit_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outfit_id', sa.Integer(), nullable=False),
    sa.Column('articulo_id', sa.Integer(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('scale', sa.Float(), nullable=False),
    sa.Column('rotation', sa.Float(), nullable=False),
    sa.Column('z_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['articulo_id'], ['articulos_propios.id'], ),
    sa.ForeignKeyConstraint(['outfit_id'], ['outfits_propios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outfit_items_id'), 'outfit_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outfit_items_id'), table_name='outfit_items')
    op.drop_table('outfit_items')
    # ### end Alembic commands ###
