"""Remove unique constraint from nombre in ArticuloPropio

Revision ID: 4d13a73675aa
Revises: 37e9b34aa242
Create Date: 2025-05-19 10:47:07.703666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d13a73675aa'
down_revision: Union[str, None] = '37e9b34aa242'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('articulos_propios_nombre_key', 'articulos_propios', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('articulos_propios_nombre_key', 'articulos_propios', ['nombre'])
    # ### end Alembic commands ###
