"""add foto field to OutfitPropio

Revision ID: 4fc252196654
Revises: eabf2ff461bd
Create Date: 2025-05-08 08:37:14.105724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fc252196654'
down_revision: Union[str, None] = 'eabf2ff461bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outfits_propios', sa.Column('foto', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outfits_propios', 'foto')
    # ### end Alembic commands ###
