"""Tablas borradas de ocasion, temporada y colores

Revision ID: 921a76accc85
Revises: 3cf6b63c0267
Create Date: 2025-04-26 11:52:38.890775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '921a76accc85'
down_revision: Union[str, None] = '3cf6b63c0267'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('articulo_propio_color')
    op.drop_table('articulo_propio_ocasion')
    op.drop_table('articulo_propio_temporada')
    op.drop_table('outfitnuevo_ocasion')
    op.drop_table('outfitpropio_ocasion')
    op.drop_table('ocasiones')
    op.drop_table('color_enum_items')
    op.drop_table('temporada_enum_items')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temporada_enum_items',
    sa.Column('temporada', postgresql.ENUM('VERANO', 'ENTRETIEMPO', 'INVIERNO', name='temporadaenum'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('temporada', name='temporada_enum_items_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('articulo_propio_ocasion',
    sa.Column('articulo_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ocasion_nombre', postgresql.ENUM('CASUAL', 'CENA', 'FORMAL', 'TRABAJO_INFORMAL', 'TRABAJO_FORMAL', 'EVENTO', name='ocasionenum'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['articulo_id'], ['articulos_propios.id'], name='articulo_propio_ocasion_articulo_id_fkey'),
    sa.ForeignKeyConstraint(['ocasion_nombre'], ['ocasiones.nombre'], name='articulo_propio_ocasion_ocasion_nombre_fkey'),
    sa.PrimaryKeyConstraint('articulo_id', 'ocasion_nombre', name='articulo_propio_ocasion_pkey')
    )
    op.create_table('color_enum_items',
    sa.Column('color', postgresql.ENUM('AMARILLO', 'NARANJA', 'ROJO', 'ROSA', 'VIOLETA', 'AZUL', 'VERDE', 'MARRON', 'GRIS', 'BLANCO', 'NEGRO', name='colorenum'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('color', name='color_enum_items_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('outfitnuevo_ocasion',
    sa.Column('outfit_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ocasion_nombre', postgresql.ENUM('CASUAL', 'CENA', 'FORMAL', 'TRABAJO_INFORMAL', 'TRABAJO_FORMAL', 'EVENTO', name='ocasionenum'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ocasion_nombre'], ['ocasiones.nombre'], name='outfitnuevo_ocasion_ocasion_nombre_fkey'),
    sa.ForeignKeyConstraint(['outfit_id'], ['outfits_nuevos.id'], name='outfitnuevo_ocasion_outfit_id_fkey'),
    sa.PrimaryKeyConstraint('outfit_id', 'ocasion_nombre', name='outfitnuevo_ocasion_pkey')
    )
    op.create_table('articulo_propio_temporada',
    sa.Column('articulo_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('temporada', postgresql.ENUM('VERANO', 'ENTRETIEMPO', 'INVIERNO', name='temporadaenum'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['articulo_id'], ['articulos_propios.id'], name='articulo_propio_temporada_articulo_id_fkey'),
    sa.ForeignKeyConstraint(['temporada'], ['temporada_enum_items.temporada'], name='articulo_propio_temporada_temporada_fkey'),
    sa.PrimaryKeyConstraint('articulo_id', 'temporada', name='articulo_propio_temporada_pkey')
    )
    op.create_table('ocasiones',
    sa.Column('nombre', postgresql.ENUM('CASUAL', 'CENA', 'FORMAL', 'TRABAJO_INFORMAL', 'TRABAJO_FORMAL', 'EVENTO', name='ocasionenum'), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('nombre', name='ocasiones_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('outfitpropio_ocasion',
    sa.Column('outfit_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ocasion_nombre', postgresql.ENUM('CASUAL', 'CENA', 'FORMAL', 'TRABAJO_INFORMAL', 'TRABAJO_FORMAL', 'EVENTO', name='ocasionenum'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ocasion_nombre'], ['ocasiones.nombre'], name='outfitpropio_ocasion_ocasion_nombre_fkey'),
    sa.ForeignKeyConstraint(['outfit_id'], ['outfits_propios.id'], name='outfitpropio_ocasion_outfit_id_fkey'),
    sa.PrimaryKeyConstraint('outfit_id', 'ocasion_nombre', name='outfitpropio_ocasion_pkey')
    )
    op.create_table('articulo_propio_color',
    sa.Column('articulo_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('color', postgresql.ENUM('AMARILLO', 'NARANJA', 'ROJO', 'ROSA', 'VIOLETA', 'AZUL', 'VERDE', 'MARRON', 'GRIS', 'BLANCO', 'NEGRO', name='colorenum'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['articulo_id'], ['articulos_propios.id'], name='articulo_propio_color_articulo_id_fkey'),
    sa.ForeignKeyConstraint(['color'], ['color_enum_items.color'], name='articulo_propio_color_color_fkey'),
    sa.PrimaryKeyConstraint('articulo_id', 'color', name='articulo_propio_color_pkey')
    )
    # ### end Alembic commands ###
