"""Añadir relación muchos a muchos para color y temporada

Revision ID: d56923441e77
Revises: 
Create Date: 2025-04-17 20:52:13.676955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd56923441e77'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('articulo_propio_color_color_fkey', 'articulo_propio_color', type_='foreignkey')
    op.drop_constraint('articulo_propio_color_articulo_id_fkey', 'articulo_propio_color', type_='foreignkey')
    op.create_foreign_key(None, 'articulo_propio_color', 'articulos_propios', ['articulo_id'], ['id'])
    op.drop_constraint('articulo_propio_temporada_temporada_fkey', 'articulo_propio_temporada', type_='foreignkey')
    op.drop_constraint('articulo_propio_temporada_articulo_id_fkey', 'articulo_propio_temporada', type_='foreignkey')
    op.create_foreign_key(None, 'articulo_propio_temporada', 'articulos_propios', ['articulo_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articulo_propio_temporada', type_='foreignkey')
    op.create_foreign_key('articulo_propio_temporada_articulo_id_fkey', 'articulo_propio_temporada', 'articulos_propios', ['articulo_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('articulo_propio_temporada_temporada_fkey', 'articulo_propio_temporada', 'temporada_enum_items', ['temporada'], ['temporada'])
    op.drop_constraint(None, 'articulo_propio_color', type_='foreignkey')
    op.create_foreign_key('articulo_propio_color_articulo_id_fkey', 'articulo_propio_color', 'articulos_propios', ['articulo_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('articulo_propio_color_color_fkey', 'articulo_propio_color', 'color_enum_items', ['color'], ['color'])
    # ### end Alembic commands ###
