"""colecciones

Revision ID: e32e92067b29
Revises: 4792a2082222
Create Date: 2025-06-02 23:40:57.354358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e32e92067b29'
down_revision: Union[str, None] = '4792a2082222'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colecciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('propietario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['propietario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_colecciones_id'), 'colecciones', ['id'], unique=False)
    op.create_table('coleccion_outfit',
    sa.Column('coleccion_id', sa.Integer(), nullable=True),
    sa.Column('outfit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['coleccion_id'], ['colecciones.id'], ),
    sa.ForeignKeyConstraint(['outfit_id'], ['outfits_propios.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coleccion_outfit')
    op.drop_index(op.f('ix_colecciones_id'), table_name='colecciones')
    op.drop_table('colecciones')
    # ### end Alembic commands ###
