"""add dos capos a outfit

Revision ID: eabf2ff461bd
Revises: ed944086a017
Create Date: 2025-05-04 16:09:08.053435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eabf2ff461bd'
down_revision: Union[str, None] = 'ed944086a017'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outfits', sa.Column('temporadas', sa.ARRAY(sa.Enum('VERANO', 'ENTRETIEMPO', 'INVIERNO', name='temporadaenum')), nullable=True))
    op.add_column('outfits', sa.Column('colores', sa.ARRAY(sa.Enum('AMARILLO', 'NARANJA', 'ROJO', 'ROSA', 'VIOLETA', 'AZUL', 'VERDE', 'MARRON', 'GRIS', 'BLANCO', 'NEGRO', name='colorenum')), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outfits', 'colores')
    op.drop_column('outfits', 'temporadas')
    # ### end Alembic commands ###
