"""eliminar articulos y outfits

Revision ID: ee651b420bb7
Revises: dad0a9d8b7b2
Create Date: 2025-05-08 13:48:37.721906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee651b420bb7'
down_revision: Union[str, None] = 'dad0a9d8b7b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    estilo_enum = sa.Enum(
        'BOHO', 'STREET', 'MINIMAL', 'ELEGANT', 'SPORTY',
        'PUNK', 'FORMAL', 'CASUAL', 'BEACH',
        name='estiloenum'
    )
    estilo_enum.create(op.get_bind())

    op.add_column('articulos_propios', sa.Column('estilo', estilo_enum, nullable=True))
    op.add_column('articulos_propios', sa.Column('formalidad', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articulos_propios', 'formalidad')
    op.drop_column('articulos_propios', 'estilo')
    # ### end Alembic commands ###
